vaadin.productionMode=true
vaadin.launch-browser=false

server.port=${PORT:8080}
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,image/svg+xml

spring.devtools.restart.enabled=false

logging.level.root=WARN
logging.level.com.example.arrows=INFO
logging.level.org.atmosphere=WARN
